"""Emit editor/js/layouts.js from the backend layout registry.

    python scripts/gen_layouts.py

The editor must place photos on exactly the rectangles the renderer draws,
so the geometry has one source of truth (app/domain/layouts.py) and this
script copies it across the language boundary. tests/domain/test_layouts.py
fails if the committed JS no longer matches.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from app.domain.layouts import DEFAULT_LAYOUT, LAYOUTS

TARGET = Path(__file__).resolve().parent.parent.parent / "editor/js/layouts.js"

HEADER = """/* GENERATED by backend/scripts/gen_layouts.py — do not edit.
   Mirror of backend/app/domain/layouts.py: the slot rectangles (trim-origin
   mm) each page layout offers. */
"""


def main() -> None:
    body = (f"{HEADER}export const LAYOUTS = "
            f"{json.dumps(LAYOUTS, indent=2, sort_keys=True)};\n"
            f"export const DEFAULT_LAYOUT = {json.dumps(DEFAULT_LAYOUT)};\n"
            "export const LAYOUT_IDS = Object.keys(LAYOUTS);\n")
    TARGET.write_text(body)
    print(f"wrote {TARGET} ({len(LAYOUTS)} layouts)")


if __name__ == "__main__":
    main()
