"""Emit editor/js/cover-templates.js from the backend template registry.

    python scripts/gen_cover_templates.py

The editor draws the cover the customer confirms, so the photo rectangle it
shows must be the one the renderer prints. One source of truth
(app/domain/cover_templates.py), copied across the language boundary here;
tests/domain/test_cover_templates.py fails if the committed JS drifts.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from app.domain.cover_templates import (  # noqa: E402
    COVER_TEMPLATES,
    DEFAULT_COVER_TEMPLATE,
    FULL_RECT,
)

TARGET = Path(__file__).resolve().parent.parent.parent / "editor/js/cover-templates.js"

HEADER = """/* GENERATED by backend/scripts/gen_cover_templates.py — do not edit.
   Mirror of backend/app/domain/cover_templates.py: where each cover design
   puts the photo (front-panel trim mm) and the title. */
"""


def main() -> None:
    # Registry order, not alphabetical: it is the order the picker shows,
    # and the default belongs first.
    body = (f"{HEADER}export const COVER_TEMPLATES = "
            f"{json.dumps(COVER_TEMPLATES, indent=2)};\n"
            f"export const DEFAULT_COVER_TEMPLATE = "
            f"{json.dumps(DEFAULT_COVER_TEMPLATE)};\n"
            f"export const FULL_COVER_RECT = {json.dumps(FULL_RECT)};\n"
            f"export const COVER_TEMPLATE_IDS = "
            f"{json.dumps(list(COVER_TEMPLATES))};\n")
    TARGET.write_text(body)
    print(f"wrote {TARGET} ({len(COVER_TEMPLATES)} templates)")


if __name__ == "__main__":
    main()
