"""Vendor the sticker assets from Noto Emoji (one-time / on registry change).

    pip install cairosvg   # build-time only, never a runtime dependency
    python scripts/vendor_stickers.py

Downloads each registry entry's SVG from the pinned Noto Emoji release,
rasterizes two PNG sets, and writes the license notice:

- app/render/stickers/<id>.png   1024px — embedded in print PDFs (sharp up
                                 to ~86mm at 300dpi, larger than any page)
- ../editor/stickers/<id>.png    1024px — editor canvas (sharp at any zoom)
- ../editor/stickers/thumb/<id>.png 128px — picker grid thumbnails

Commit the results. The renderers and editor read only these files; nothing
touches the network at runtime.
"""
import json
import math
import sys
from pathlib import Path

import cairosvg
import httpx

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from app.domain.stickers import (
    COUNTRIES,
    DECORATIVE,
    NATURAL_EARTH_TAG,
    NOTO_EMOJI_TAG,
)

NOTO_RAW = ("https://raw.githubusercontent.com/googlefonts/noto-emoji/"
            f"{NOTO_EMOJI_TAG}/svg/emoji_u{{seq}}.svg")
# Rectangular country flags: the region-flags set vendored inside noto-emoji
# (sourced from Wikipedia, checked Public Domain — see its LICENSE).
FLAG_RAW = ("https://raw.githubusercontent.com/googlefonts/noto-emoji/"
            f"{NOTO_EMOJI_TAG}/third_party/region-flags/svg/{{iso}}.svg")
NE_GEOJSON = ("https://raw.githubusercontent.com/nvkelso/natural-earth-vector/"
              f"{NATURAL_EARTH_TAG}/geojson/ne_50m_admin_0_countries.geojson")
BACKEND_DIR = Path(__file__).resolve().parent.parent / "app/render/stickers"
EDITOR_DIR = Path(__file__).resolve().parent.parent.parent / "editor/stickers"
THUMB_DIR = EDITOR_DIR / "thumb"

MAP_FILL = "#1d4d85"     # deep blue silhouette...
MAP_STROKE = "#ffffff"   # ...with a white halo so it reads on photos too

NOTICE = f"""# Sticker assets — license notice

- Decorative stickers are rasterized from the
  [Noto Emoji](https://github.com/googlefonts/noto-emoji) project,
  release `{NOTO_EMOJI_TAG}`, © Google and Noto Project contributors,
  licensed under the Apache License, Version 2.0
  (http://www.apache.org/licenses/LICENSE-2.0).
- Country flags (`flag-*.png`) come from the region-flags collection
  vendored inside the same noto-emoji release
  (`third_party/region-flags`): Wikipedia-sourced images checked to be in
  the Public Domain or otherwise exempt from copyright (see that
  directory's LICENSE).
- Country map silhouettes (`map-*.png`) are generated by our vendor script
  from [Natural Earth](https://www.naturalearthdata.com/) 1:50m data
  (release `{NATURAL_EARTH_TAG}`), which is in the public domain. The
  rendered silhouettes are simplified illustrations, not precise maps.

Vendored by `backend/scripts/vendor_stickers.py`; the registry lives in
`backend/app/domain/stickers.py`. Regenerate by re-running the script —
never edit these files by hand.
"""


def write_png(sticker_id: str, svg: bytes) -> None:
    for target, size in ((BACKEND_DIR, 1024), (EDITOR_DIR, 1024),
                         (THUMB_DIR, 128)):
        png = cairosvg.svg2png(bytestring=svg, output_width=size,
                               output_height=size)
        (target / f"{sticker_id}.png").write_bytes(png)


def write_flag_png(sticker_id: str, svg: bytes) -> None:
    """Flags keep their real aspect ratio, centred on a transparent square,
    with a hairline border so white flag bands read on white pages."""
    import io

    from PIL import Image, ImageDraw

    for target, size in ((BACKEND_DIR, 1024), (EDITOR_DIR, 1024),
                         (THUMB_DIR, 128)):
        png = cairosvg.svg2png(bytestring=svg, output_width=size)
        flag = Image.open(io.BytesIO(png)).convert("RGBA")
        if flag.height > size:
            flag = flag.resize((round(flag.width * size / flag.height), size),
                               resample=Image.LANCZOS)
        canvas = Image.new("RGBA", (size, size), (0, 0, 0, 0))
        x = (size - flag.width) // 2
        y = (size - flag.height) // 2
        canvas.paste(flag, (x, y), flag)
        draw = ImageDraw.Draw(canvas)
        draw.rectangle([x, y, x + flag.width - 1, y + flag.height - 1],
                       outline=(0, 0, 0, 46), width=max(1, size // 256))
        out = io.BytesIO()
        canvas.save(out, format="PNG")
        (target / f"{sticker_id}.png").write_bytes(out.getvalue())


# ---------- country silhouettes from Natural Earth ---------------------------

def _polys(geometry: dict) -> list:
    if geometry["type"] == "Polygon":
        return [geometry["coordinates"]]
    return list(geometry["coordinates"])


def _ring_area(ring: list) -> float:
    s = 0.0
    for (x1, y1), (x2, y2) in zip(ring, ring[1:] + ring[:1], strict=True):
        s += x1 * y2 - x2 * y1
    return abs(s) / 2


def _centroid(ring: list) -> tuple[float, float]:
    return (sum(p[0] for p in ring) / len(ring),
            sum(p[1] for p in ring) / len(ring))


def country_svg(geometry: dict) -> str:
    """One country -> a square silhouette SVG. Deliberately illustrative:
    the mainland plus nearby/large islands; far-flung overseas territories
    are dropped so e.g. France looks like France."""
    polys = _polys(geometry)

    # Antimeridian-crossing countries (Russia, USA): shift west longitudes
    # +360 so the shape is contiguous.
    lons = [p[0] for poly in polys for p in poly[0]]
    if max(lons) - min(lons) > 180:
        polys = [[[(lon + 360 if lon < 0 else lon, lat) for lon, lat in ring]
                  for ring in poly] for poly in polys]
    else:
        polys = [[[(lon, lat) for lon, lat in ring] for ring in poly]
                 for poly in polys]

    areas = [_ring_area(poly[0]) for poly in polys]
    biggest = max(areas)
    main_lon, main_lat = _centroid(polys[areas.index(biggest)][0])
    kept = []
    for poly, area in zip(polys, areas, strict=True):
        if area < biggest * 0.001:
            continue   # speck islands only add noise at sticker size
        lon, lat = _centroid(poly[0])
        near = abs(lon - main_lon) < 30 and abs(lat - main_lat) < 20
        if near or area >= biggest * 0.3:
            kept.append(poly)

    # Equirectangular projection scaled by cos(lat) for a sane aspect.
    k = math.cos(math.radians(main_lat))
    pts = [(lon * k, -lat) for poly in kept for p_ring in poly for lon, lat in p_ring]
    min_x = min(p[0] for p in pts)
    max_x = max(p[0] for p in pts)
    min_y = min(p[1] for p in pts)
    max_y = max(p[1] for p in pts)
    span = max(max_x - min_x, max_y - min_y) or 1.0
    pad = 0.08 * 1024
    scale = (1024 - 2 * pad) / span
    off_x = (1024 - (max_x - min_x) * scale) / 2
    off_y = (1024 - (max_y - min_y) * scale) / 2

    def xy(lon: float, lat: float) -> str:
        x = off_x + (lon * k - min_x) * scale
        y = off_y + (-lat - min_y) * scale
        return f"{x:.1f},{y:.1f}"

    parts = []
    for poly in kept:
        for ring in poly:   # exterior + holes; evenodd handles the holes
            parts.append("M" + "L".join(xy(lon, lat) for lon, lat in ring) + "Z")
    d = "".join(parts)
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024">'
        f'<path d="{d}" fill="{MAP_FILL}" fill-rule="evenodd" '
        f'stroke="{MAP_STROKE}" stroke-width="8" stroke-linejoin="round"/>'
        "</svg>"
    )


def vendor_maps() -> list[str]:
    print(f"downloading Natural Earth {NATURAL_EARTH_TAG} (~25MB)...")
    resp = httpx.get(NE_GEOJSON, timeout=300)
    resp.raise_for_status()
    features = json.loads(resp.content)["features"]
    by_iso = {}
    for feat in features:
        props = feat["properties"]
        iso = (props.get("ISO_A2_EH") or props.get("ISO_A2") or "").lower()
        if iso and iso != "-99":
            by_iso[iso] = feat
    failed = []
    for iso in sorted(COUNTRIES):
        feat = by_iso.get(iso)
        if feat is None:
            failed.append(f"map-{iso}: no Natural Earth feature")
            continue
        svg = country_svg(feat["geometry"]).encode()
        write_png(f"map-{iso}", svg)
        print(f"  ok map-{iso} ({COUNTRIES[iso]})")
    return failed


# ---------- noto emoji: decorative packs + flags -----------------------------

def vendor_noto() -> list[str]:
    failed = []
    for sticker_id, (seq, _cat) in sorted(DECORATIVE.items()):
        resp = httpx.get(NOTO_RAW.format(seq=seq), timeout=30)
        if resp.status_code != 200:
            failed.append(f"{sticker_id}: HTTP {resp.status_code}")
            print(f"  !! {sticker_id}: HTTP {resp.status_code}")
            continue
        write_png(sticker_id, resp.content)
        print(f"  ok {sticker_id}")
    for iso in sorted(COUNTRIES):
        resp = httpx.get(FLAG_RAW.format(iso=iso.upper()), timeout=30)
        if resp.status_code != 200:
            failed.append(f"flag-{iso}: HTTP {resp.status_code}")
            print(f"  !! flag-{iso}: HTTP {resp.status_code}")
            continue
        write_flag_png(f"flag-{iso}", resp.content)
        print(f"  ok flag-{iso}")
    return failed


def main() -> None:
    BACKEND_DIR.mkdir(parents=True, exist_ok=True)
    EDITOR_DIR.mkdir(parents=True, exist_ok=True)
    THUMB_DIR.mkdir(parents=True, exist_ok=True)
    failed = vendor_noto() + vendor_maps()
    (BACKEND_DIR / "LICENSE-NOTICE.md").write_text(NOTICE)
    (EDITOR_DIR / "LICENSE-NOTICE.md").write_text(NOTICE)
    if failed:
        sys.exit(f"{len(failed)} assets failed: {failed}")
    print(f"done (print: {BACKEND_DIR}, editor: {EDITOR_DIR})")


if __name__ == "__main__":
    main()
