/* GENERATED by backend/scripts/gen_layouts.py — do not edit.
   Mirror of backend/app/domain/layouts.py: the slot rectangles (trim-origin
   mm) each page layout offers. */
export const LAYOUTS = {
  "big-top": [
    {
      "h_mm": 133.92,
      "w_mm": 154.0,
      "x_mm": -3.0,
      "y_mm": -3.0
    },
    {
      "h_mm": 80.08,
      "w_mm": 76.0,
      "x_mm": -3.0,
      "y_mm": 132.92
    },
    {
      "h_mm": 80.08,
      "w_mm": 76.0,
      "x_mm": 75.0,
      "y_mm": 132.92
    }
  ],
  "four": [
    {
      "h_mm": 107.0,
      "w_mm": 76.0,
      "x_mm": -3.0,
      "y_mm": -3.0
    },
    {
      "h_mm": 107.0,
      "w_mm": 76.0,
      "x_mm": 75.0,
      "y_mm": -3.0
    },
    {
      "h_mm": 107.0,
      "w_mm": 76.0,
      "x_mm": -3.0,
      "y_mm": 106.0
    },
    {
      "h_mm": 107.0,
      "w_mm": 76.0,
      "x_mm": 75.0,
      "y_mm": 106.0
    }
  ],
  "full": [
    {
      "h_mm": 216.0,
      "w_mm": 154.0,
      "x_mm": -3.0,
      "y_mm": -3.0
    }
  ],
  "inset": [
    {
      "h_mm": 186.0,
      "w_mm": 124.0,
      "x_mm": 12,
      "y_mm": 12
    }
  ],
  "three-v": [
    {
      "h_mm": 70.67,
      "w_mm": 154.0,
      "x_mm": -3.0,
      "y_mm": -3.0
    },
    {
      "h_mm": 70.67,
      "w_mm": 154.0,
      "x_mm": -3.0,
      "y_mm": 69.67
    },
    {
      "h_mm": 70.67,
      "w_mm": 154.0,
      "x_mm": -3.0,
      "y_mm": 142.33
    }
  ],
  "two-h": [
    {
      "h_mm": 216.0,
      "w_mm": 76.0,
      "x_mm": -3.0,
      "y_mm": -3.0
    },
    {
      "h_mm": 216.0,
      "w_mm": 76.0,
      "x_mm": 75.0,
      "y_mm": -3.0
    }
  ],
  "two-v": [
    {
      "h_mm": 107.0,
      "w_mm": 154.0,
      "x_mm": -3.0,
      "y_mm": -3.0
    },
    {
      "h_mm": 107.0,
      "w_mm": 154.0,
      "x_mm": -3.0,
      "y_mm": 106.0
    }
  ]
};
export const DEFAULT_LAYOUT = "full";
export const LAYOUT_IDS = Object.keys(LAYOUTS);
