"""Sticker registry — the single source of truth for which stickers exist.

Three vendored sources, all print-safe, all pinned and committed by
scripts/vendor_stickers.py exactly like the render fonts (no runtime
network dependency, deterministic renders forever):

- decorative packs + country FLAGS: Noto Emoji SVGs (Apache-2.0)
- country MAP silhouettes: generated by us from Natural Earth data
  (public domain) — see app/render/stickers/LICENSE-NOTICE.md

Keys are stable public ids (they live in saved layouts — never rename).
"""

NOTO_EMOJI_TAG = "v2.048"
NATURAL_EARTH_TAG = "v5.1.2"

# Curated countries (iso2 -> display name): Uzbekistan + neighbours/CIS +
# the destinations Uzbek travellers actually fly to. Each gets a flag
# sticker (flag-<iso>) and a map-silhouette sticker (map-<iso>). Extend
# freely — re-run the vendor script after.
COUNTRIES: dict[str, str] = {
    "uz": "Uzbekistan", "kz": "Kazakhstan", "kg": "Kyrgyzstan",
    "tj": "Tajikistan", "tm": "Turkmenistan", "ru": "Russia",
    "az": "Azerbaijan", "ge": "Georgia", "am": "Armenia",
    "by": "Belarus", "ua": "Ukraine",
    "tr": "Turkey", "ae": "UAE", "sa": "Saudi Arabia", "qa": "Qatar",
    "eg": "Egypt", "th": "Thailand", "my": "Malaysia", "id": "Indonesia",
    "in": "India", "cn": "China", "kr": "South Korea", "jp": "Japan",
    "sg": "Singapore", "vn": "Vietnam", "mv": "Maldives",
    "de": "Germany", "fr": "France", "it": "Italy", "es": "Spain",
    "gb": "United Kingdom", "nl": "Netherlands", "ch": "Switzerland",
    "at": "Austria", "cz": "Czechia", "gr": "Greece", "pl": "Poland",
    "us": "United States", "ca": "Canada", "br": "Brazil", "au": "Australia",
}


def flag_noto_seq(iso: str) -> str:
    """Flags are emoji: two regional-indicator codepoints from the iso2."""
    return "_".join(f"{0x1F1E6 + ord(ch) - ord('a'):x}" for ch in iso)


# Decorative packs: id -> (noto codepoint sequence, category).
DECORATIVE: dict[str, tuple[str, str]] = {
    # --- travel ---
    "airplane": ("2708", "travel"),
    "luggage": ("1f9f3", "travel"),
    "camera": ("1f4f7", "travel"),
    "camera-flash": ("1f4f8", "travel"),
    "compass": ("1f9ed", "travel"),
    "world-map": ("1f5fa", "travel"),
    "globe": ("1f30d", "travel"),
    "palm-tree": ("1f334", "travel"),
    "desert-island": ("1f3dd", "travel"),
    "beach-umbrella": ("1f3d6", "travel"),
    "mountain": ("26f0", "travel"),
    "tent": ("26fa", "travel"),
    "train": ("1f682", "travel"),
    "ship": ("1f6a2", "travel"),
    "anchor": ("2693", "travel"),
    "footprints": ("1f463", "travel"),
    "pushpin": ("1f4cd", "travel"),
    "sun": ("2600", "travel"),
    # --- love ---
    "heart": ("2764", "love"),
    "two-hearts": ("1f495", "love"),
    "sparkling-heart": ("1f496", "love"),
    "heart-arrow": ("1f498", "love"),
    "revolving-hearts": ("1f49e", "love"),
    "heart-ribbon": ("1f49d", "love"),
    "rose": ("1f339", "love"),
    "bouquet": ("1f490", "love"),
    "ring": ("1f48d", "love"),
    "love-letter": ("1f48c", "love"),
    "kiss-mark": ("1f48b", "love"),
    # --- birthday ---
    "birthday-cake": ("1f382", "birthday"),
    "balloon": ("1f388", "birthday"),
    "party-popper": ("1f389", "birthday"),
    "confetti-ball": ("1f38a", "birthday"),
    "gift": ("1f381", "birthday"),
    "cupcake": ("1f9c1", "birthday"),
    "lollipop": ("1f36d", "birthday"),
    "crown": ("1f451", "birthday"),
    "candle": ("1f56f", "birthday"),
    # --- nature ---
    "rainbow": ("1f308", "nature"),
    "cherry-blossom": ("1f338", "nature"),
    "sunflower": ("1f33b", "nature"),
    "tulip": ("1f337", "nature"),
    "hibiscus": ("1f33a", "nature"),
    "clover": ("1f340", "nature"),
    "maple-leaf": ("1f341", "nature"),
    "butterfly": ("1f98b", "nature"),
    "snowflake": ("2744", "nature"),
    "star": ("2b50", "nature"),
    "glowing-star": ("1f31f", "nature"),
    "crescent-moon": ("1f319", "nature"),
    # --- party / fun ---
    "sparkles": ("2728", "party"),
    "fire": ("1f525", "party"),
    "musical-notes": ("1f3b6", "party"),
    "clinking-glasses": ("1f942", "party"),
    "pizza": ("1f355", "party"),
    "ice-cream": ("1f366", "party"),
    "watermelon": ("1f349", "party"),
    "strawberry": ("1f353", "party"),
    "coffee": ("2615", "party"),
    "soccer-ball": ("26bd", "party"),
    "gamepad": ("1f3ae", "party"),
    "rocket": ("1f680", "party"),
    # --- misc ---
    "speech-balloon": ("1f4ac", "misc"),
    "thought-balloon": ("1f4ad", "misc"),
    "hundred": ("1f4af", "misc"),
    "paw-prints": ("1f43e", "misc"),
    "dog": ("1f436", "misc"),
    "cat": ("1f431", "misc"),
    "panda": ("1f43c", "misc"),
    "unicorn": ("1f984", "misc"),
    "teddy-bear": ("1f9f8", "misc"),
    "graduation-cap": ("1f393", "misc"),
    "books": ("1f4da", "misc"),
}

CATEGORIES = ("flags", "maps", "travel", "love", "birthday", "nature",
              "party", "misc")

# The full public registry: id -> category.
STICKERS: dict[str, str] = (
    {f"flag-{iso}": "flags" for iso in COUNTRIES}
    | {f"map-{iso}": "maps" for iso in COUNTRIES}
    | {sticker_id: category for sticker_id, (_seq, category)
       in DECORATIVE.items()}
)


def sticker_ids() -> frozenset[str]:
    return frozenset(STICKERS)
